services:
  db:
    image: postgres:15-alpine
    container_name: acme_db
    restart: always
    environment:
      POSTGRES_USER: acme_admin
      POSTGRES_PASSWORD: acme_password
      POSTGRES_DB: acme_finanzas
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: acme_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@acme.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
